export default class Utils {
  static schoolList=[
    ["Milburn High School"],
    ["Montgomery High School"],
    ["Bergen County Academies"],
    ["Princeton High School", "PHS"],
    ["Freehold High School"],
    ["Robbinsville High School"],
    ["HightsTown High School"],
    ["Stuyvesant High School"],
    ["East Stroudsburg High School"],
    ["Livingston High School"],
    ["Princeton Day School", "PDS"],
    ["Noor-ul-Iman", "Noor ul Iman"],
    ["Wardlaw + Hartridge School"],
    ["South Brunswick High School"],
    ["Ridge High School"],
    ["West Windsor Plainsborough High North", "WWP", "North"],
    ["West Windsor Plainsborough High South", "WWP", "South"],
    ["Middlesex County Academy"],
    ["Perth Amboy Vocational Technical School"],
    ["Raritan High School"],
    ["Pennington School"],
    ["Manav Rachna International"],
    ["Edison Academy"],
    ["Port Credit Secondary School"],
    ["John P. Stevens High School", "J.P. Stevens"],
    ['Point Pleasant Beach High School'],
    ['Great Neck South High School'],
    ['Monroe Township High School'],
    ['Newark Charter Junior/Senior High School', 'Newark Charter High School'],
    ["Simsbury High School"],
    ["Egg Harbor Township High School"],
    ["Roxbury High School"],
    ["Souderton Area High School"],
    ["Hillsborough High School"],
    ["Perth Amboy High School"],
    ["Bronx High School Of Science"],
    ["High Technology High School"],
    ["Middlesex County Academy For Allied Health And Biomedical Sciences"],
    ["Baltimore Polytechnic Institute"],
    ["Thomas Jefferson High School For Science And Technology"],
    ["Council Rock High School North"],
    ["Mountain Lakes High School"],
    ["Wellington C. Mepham Highschool"],
    ["Jackson Memorial High School"],
    ["Morris Hills High School"],
    ["Burlington Township High School"],
    ["Briarcliff High School"],
    ["Spotswood High School"],
    ["Clifton Public Highschool"],
    ["Rutgers Preparatory School"],
    ["Marlboro High School"],
    ["Homeschool"],
    ["Montclair High School"],
    ["Episcopal Academy"],
    ["Foundation Collegiate Academy"],
    ["Warren County Technical High School"],
    ["Franklin High School"],
    ["Solebury School"],
    ["Colts Neck High School"],
    ["Bordentown Regional High School"],
    ["North Brunswick Township High School"],
    ["Rye High School"],
    ["Oratary Prep School At Summit"],
    ["Staten Island Technical High"],
    ["Princeton International School Of Mathematics And Science"],
    ["The Lawrenceville School"],
    ["Steinert High School"],
    ["West Essex Regional High School"],
    ["Kingsway Regional High School"],
  ];

  static hardwareList=[
    ["Servos"],
    ["Motors"],
    ["Arduino or other microcontrollers", "ESP", "ESP-32"]
  ];
}
